export const GET_COMMENTS_FOR_POST = 'GET_COMMENTS_FOR_POST';
export const SET_COMMENTS_FOR_POST = 'SET_COMMENTS_FOR_POST';
export const ADD_COMMENT_TO_POST = 'ADD_COMMENT_TO_POST';

export const GET_REACTEES_FOR_POST = 'GET_REACTEES_FOR_POST';
export const SET_REACTEES_FOR_POST = 'SET_REACTEES_FOR_POST';
