export const SET_COLLECTIONS = 'SET_COLLECTIONS';
export const GET_COLLECTIONS = 'GET_COLLECTIONS';

export const GET_PRODUCTS_BY_COLLECTION = 'GET_PRODUCTS_BY_COLLECTION';
export const SET_PRODUCTS_BY_COLLECTION = 'SET_PRODUCTS_BY_COLLECTION';

export const GET_ALL_REWARDS = 'GET_ALL_REWARDS';
export const SET_ALL_REWARDS = 'SET_ALL_REWARDS';

export const REFRESH_REWARDS = 'REFRESH_REWARDS';
export const SET_REWARDS_LOADING = 'SET_REWARDS_LOADING';

export const RESET_REWARDS = 'RESET_REWARDS';
