export const OPEN_ALERT_MODAL = 'OPEN_ALERT_MODAL';
export const CLOSE_ALERT_MODAL = 'CLOSE_ALERT_MODAL';

export const OPEN_CONFIRM_MODAL = 'OPEN_CONFIRM_MODAL';
export const CLOSE_CONFIRM_MODAL = 'CLOSE_CONFIRM_MODAL';

export const GET_APP_DATA = 'GET_APP_DATA';
export const GET_RECOGNITION_BADGES = 'GET_RECOGNITION_BADGES';
export const SET_BADGES = 'SET_BADGES';
export const GET_RECOGNITION_IMAGES = 'GET_RECOGNITION_IMAGES';
export const SET_RECOGNITION_IMAGES = 'SET_RECOGNITION_IMAGES';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
