export const SEND_RECOGNITION = 'SEND_RECOGNITION';
export const GET_RECOGNITIONS = 'GET_RECOGNITIONS';

export const SET_RECOGNITIONS = 'SET_RECOGNITIONS';
export const ADD_RECOGNITION = 'ADD_RECOGNITION';

export const GET_SENT_RECOGNITIONS = 'GET_SENT_RECOGNITIONS';
export const SET_SENT_RECOGNITIONS = 'SET_SENT_RECOGNITIONS';
export const ADD_SENT_RECOGNITION = 'ADD_SENT_RECOGNITION';

export const GET_RECEIVED_RECOGNITIONS = 'GET_RECEIVED_RECOGNITIONS';
export const SET_RECEIVED_RECOGNITIONS = 'SET_RECEIVED_RECOGNITIONS';
export const ADD_RECEIVED_RECOGNITION = 'ADD_RECEIVED_RECOGNITION';

export const SET_TOP_VALUES = 'SET_TOP_VALUES';
export const GET_TOP_VALUES = 'GET_TOP_VALUES';

export const TRIGGER_HOME_SCROLLING = 'TRIGGER_HOME_SCROLLING';

export const RESET_RECOGNITION = 'RESET_RECOGNITION';

export const INCREASE_COMMENTS_NUMBER = 'INCREASE_COMMENTS_NUMBER';
export const INCREASE_REACTION_NUMBER = 'INCREASE_REACTION_NUMBER';
export const DECREASE_REACTION_NUMBER = 'DECREASE_REACTION_NUMBER';
